name: Deploy to Live Website ðŸš€

on:
  push:
    branches: ["main"]

# GitHub ko permission do ki wo website file write kar sake
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job 1: Check & Build
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Code Download
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Pages (GitHub ka tool)
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # 3. Upload Artifact (Code ko pack karke server pe upload)
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      # 4. Deploy (Live kar do)
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2